<a href="https://colab.research.google.com/github/Aaaaddddyyyyyyyy/Deep-Learning/blob/main/Backpropagation_in_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]],columns=['cgpa','profile_score','lpa'])      #making dataframe


In [ ]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,5,12,7


In [ ]:
def intialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L=len(layer_dims) # Corrected: layer_dim -> layer_dims

  for l in range(1,L):
    # Corrected: use 'l' for iteration, and correct dimensions for W and b
    parameters['W'+str(l)]= np.ones((layer_dims[l],layer_dims[l-1]))*0.1
    parameters['b'+str(l)]=np.zeros((layer_dims[l],1))

  return parameters

In [ ]:
intialize_parameters([2,2,1])    # initialize architecture of neural network

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev,W,b):
  Z= np.dot(W.T,A_prev)+b
  return Z

In [ ]:
## Forward propagation
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)  //2        ## no of layers in neural network

  for i in range(1,L+1):
    A_prev= A
    W1= parameters['W'+str(1)]
    b1= parameters['b'+str(1)]
    print("A"+str(i-1)+":",A_prev)
    print("W"+str(i)+":",W1)
    print("b"+str(i)+":",b1)
    print("-"*20)


    A=linear_forward(A_prev,W1,b1)
    print("A"+str(i)+": ",A)
  return A,A_prev

In [ ]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

# parameter intialize
parameters=intialize_parameters([2,2,1])

L_layer_forward(X,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
--------------------
A1:  [[1.6]
 [1.6]]
A1: [[1.6]
 [1.6]]
W2: [[0.1 0.1]
 [0.1 0.1]]
b2: [[0.]
 [0.]]
--------------------
A2:  [[0.32]
 [0.32]]


(array([[0.32],
        [0.32]]),
 array([[1.6],
        [1.6]]))

In [ ]:
(y-0.32)**2   ## loss of first student

np.float64(13.5424)

In [ ]:
X       #input of 1st student

array([[8],
       [8]])

In [ ]:
y       # output value

np.int64(4)

In [ ]:
## update weights and bias
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0]=parameters['W2'][0][0]+(0.001*2*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0]=parameters['W2'][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0]=parameters['W2'][1][0]+(0.001*2(y-y_hat))

  parameters['W1'][0][0]=parameters['W1'][0][0]+(0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1]=parameters['W1'][0][1]+(0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0]=parameters['W1'][1][0]+(0.001*2(y-y_hat)*parameters['W2'][0][0]*X[0][0])

  parameters['W1'][1][0]=parameters['W1'][1][0]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1]=parameters['W1'][1][1]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0]+(0.001*2(y-y_hat)*parameters['W2'][1][0])

<>:5: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:9: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:13: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:5: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:9: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:13: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_2021/788745241.py:5: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  parameters['b2'][0][0]=parameters['W2'][1][0]+(0.001*2(y-y_hat))
/tmp/ipykernel_2021/788745241.py:9: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  parameters['b1'][0][0]=parameters['W1'][1][0]+(0.001*2(y-y_hat)*parameters['W2'][0][0]*X[0][0])
/tmp/ipykernel_2021/788745241.py:13: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  parameters['b1'][1][0]=parame

In [26]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)   # shape= no of features , no of training examples
y=df[['lpa']].values[0][0]

# parameter intialize


In [27]:
## using keras

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [28]:
# Neural network architecture
model= Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.get_weights()   ## randomly gets weights

[array([[ 0.23309207,  0.24346864],
        [ 0.4578222 , -0.26282102]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.2798463],
        [1.1852521]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
## new weights and bias
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),           ## weights=0.1 bias= 0
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [37]:
model.set_weights(new_weights)


In [38]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [39]:
## setting learning rate
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [40]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 26.5048
Epoch 2/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.3038
Epoch 3/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 26.0680
Epoch 4/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.8018
Epoch 5/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.5673
Epoch 6/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25.3066
Epoch 7/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.0822
Epoch 8/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.7895
Epoch 9/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 24.5249
Epoch 10/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24.2586
Epoch 11/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.9995
Epoch 12/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.6864
Epoch 13/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.4122
Epoch 14/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.1152
Epoch 15/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.7981
Epoch 16/75
3/3 ━━━

In [41]:
model.get_weights()

[array([[0.3315799 , 0.3315799 ],
        [0.31574133, 0.31574133]], dtype=float32),
 array([0.22616212, 0.22616212], dtype=float32),
 array([[0.32588565],
        [0.32588565]], dtype=float32),
 array([0.17731972], dtype=float32)]